# Generated by Django 3.2.4 on 2021-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrio',
            options={'ordering': ['numero_parques'], 'verbose_name_plural': 'Barrios'},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'ordering': ['tipo_parroquia'], 'verbose_name_plural': 'Parroquias'},
        ),
        migrations.AlterField(
            model_name='barrio',
            name='numero_parques',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), (6, '6')]),
        ),
    ]
