# Generated by Django 3.2.4 on 2021-06-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0002_auto_20210612_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='numero_parques',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
    ]
